"""StrategyDNA Core -- declarative genome format for autonomous trading strategies.

FreqHub-compatible .sdna format: YAML frontmatter + JSON body.
"""

from strategydna.attestation import (
    compute_attestation_hash,
    create_attestation,
    create_walkforward_attestation,
    from_attestation_json,
    stamp_attestation,
    to_attestation_json,
    verify_attestation,
    verify_attestation_chain,
)
from strategydna.canon import compute_hash, display_hash, from_sdna, stamp, to_sdna, verify
from strategydna.compiler import compile_config, compile_genome
from strategydna.models import (
    AttestationStatus,
    CompositeAndSignal,
    CompositeOrSignal,
    CustomSignal,
    Exchange,
    Frontmatter,
    GenomeBody,
    GenomeDocument,
    IndicatorCrossSignal,
    PatternSignal,
    PositionSize,
    RegimeFilter,
    RiskModel,
    SignalSet,
    StopLoss,
    TakeProfit,
    ThresholdCrossSignal,
)
from strategydna.registry import (
    LeaderboardEntry,
    Registry,
    RegistryEntry,
    RegistryIndex,
    RegistrySnapshot,
)
from strategydna.scoring import (
    RegistryScore,
    RegistryTier,
    compute_adoption_score,
    compute_backtest_score,
    compute_composite_score,
    compute_robustness_score,
    derive_tier,
    score_entry,
)
from strategydna.verification import (
    Attestation,
    AttestationVerdict,
    BacktestMetrics,
    DatasetManifest,
    EnvironmentFingerprint,
    FoldJobType,
    FoldResult,
    LossFunction,
    WalkForwardConfig,
    WalkForwardRecord,
    WindowType,
)

__version__ = "0.1.0"

__all__ = [
    "Attestation",
    "AttestationStatus",
    "AttestationVerdict",
    "BacktestMetrics",
    "CompositeAndSignal",
    "CompositeOrSignal",
    "CustomSignal",
    "DatasetManifest",
    "EnvironmentFingerprint",
    "Exchange",
    "FoldJobType",
    "FoldResult",
    "Frontmatter",
    "GenomeBody",
    "GenomeDocument",
    "IndicatorCrossSignal",
    "LeaderboardEntry",
    "LossFunction",
    "PatternSignal",
    "PositionSize",
    "RegimeFilter",
    "Registry",
    "RegistryEntry",
    "RegistryIndex",
    "RegistryScore",
    "RegistrySnapshot",
    "RegistryTier",
    "RiskModel",
    "SignalSet",
    "StopLoss",
    "TakeProfit",
    "ThresholdCrossSignal",
    "WalkForwardConfig",
    "WalkForwardRecord",
    "WindowType",
    "compile_config",
    "compile_genome",
    "compute_adoption_score",
    "compute_attestation_hash",
    "compute_backtest_score",
    "compute_composite_score",
    "compute_hash",
    "compute_robustness_score",
    "create_attestation",
    "create_walkforward_attestation",
    "derive_tier",
    "display_hash",
    "from_attestation_json",
    "from_sdna",
    "score_entry",
    "stamp",
    "stamp_attestation",
    "to_attestation_json",
    "to_sdna",
    "verify",
    "verify_attestation",
    "verify_attestation_chain",
]
