"""Compile a GenomeDocument into a FreqTrade IStrategy Python source file.

Supports FreqHub signal types: threshold_cross, indicator_cross,
composite_and, composite_or, pattern, custom.
"""

from __future__ import annotations

import json
import re
import textwrap
from typing import Any

from strategydna.indicators import get_indicator, normalize_params, resolve_column_name
from strategydna.models import GenomeDocument

STRATEGY_TEMPLATE = '''\
"""
{description}

Auto-generated by StrategyDNA compiler from genome: {genome_hash}
"""
from freqtrade.strategy import IStrategy
import talib.abstract as ta
from pandas import DataFrame
{extra_imports}

class {class_name}(IStrategy):
    """
    {description}

    Genome hash: {genome_hash}
    """

    INTERFACE_VERSION = 3

    minimal_roi = {minimal_roi}

    stoploss = {stoploss}

    timeframe = "{timeframe}"

    trailing_stop = {trailing_stop}
    trailing_stop_positive = {trailing_stop_positive}
    trailing_stop_positive_offset = {trailing_stop_positive_offset}
    trailing_only_offset_is_reached = {trailing_only_offset_is_reached}

    process_only_new_candles = True
    use_exit_signal = True
    exit_profit_only = False
    ignore_roi_if_entry_signal = False

    startup_candle_count: int = {startup_candle_count}
{can_short}
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
{indicator_code}
        return dataframe

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
{entry_code}
        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
{exit_code}
        return dataframe
'''


def compile_genome(doc: GenomeDocument) -> str:
    """Compile a GenomeDocument to a FreqTrade IStrategy Python source string."""
    class_name = _sanitize_class_name(doc.frontmatter.name or "GeneratedStrategy")
    description = doc.frontmatter.description or doc.frontmatter.name or "Auto-generated strategy"

    indicators: set[str] = set()

    # Build entry/exit conditions from signal slots
    entry_long = _signal_to_condition(doc.body.signals.entry_long, indicators)
    exit_long = _signal_to_condition(doc.body.signals.exit_long, indicators)
    entry_short = _signal_to_condition(doc.body.signals.entry_short, indicators)
    exit_short = _signal_to_condition(doc.body.signals.exit_short, indicators)

    # Regime filter
    regime_cond = None
    if doc.body.regime_filter.enabled and doc.body.regime_filter.detector:
        rf = doc.body.regime_filter
        if rf.detector == "adx_regime":
            period = rf.params.get("period", 14)
            threshold = rf.params.get("threshold", 25)
            indicators.add(json.dumps({"name": "adx", "params": {"period": period}}))
            regime_cond = f"(dataframe['adx'] > {threshold})"

    # Generate indicator code
    indicator_code = _build_indicator_code(indicators)

    # Risk extraction
    risk = doc.body.risk
    stoploss, trailing, roi = _extract_risk(risk)

    # Determine if we need qtpylib
    needs_qtpylib = _needs_qtpylib(doc.body.signals.entry_long) or \
                    _needs_qtpylib(doc.body.signals.exit_long) or \
                    _needs_qtpylib(doc.body.signals.entry_short) or \
                    _needs_qtpylib(doc.body.signals.exit_short)

    extra_imports = ""
    if needs_qtpylib:
        extra_imports = "\nimport freqtrade.vendor.qtpylib.indicators as qtpylib"

    # Build entry code
    entry_code = _build_entry_exit_code(entry_long, regime_cond, "enter_long")
    if entry_short:
        entry_code += "\n" + _build_entry_exit_code(entry_short, regime_cond, "enter_short")
    if not entry_code.strip():
        entry_code = "        pass"

    # Build exit code
    exit_code = _build_entry_exit_code(exit_long, None, "exit_long")
    if exit_short:
        exit_code += "\n" + _build_entry_exit_code(exit_short, None, "exit_short")
    if not exit_code.strip():
        exit_code = "        pass"

    # can_short
    can_short_line = ""
    if entry_short or exit_short:
        can_short_line = "\n    can_short = True\n"

    # Startup candle count
    startup = _compute_startup_candles(indicators)

    return STRATEGY_TEMPLATE.format(
        class_name=class_name,
        description=description,
        genome_hash=doc.frontmatter.hash or "unstamped",
        minimal_roi=roi,
        stoploss=stoploss,
        timeframe=doc.body.timeframe,
        trailing_stop=trailing["stop"],
        trailing_stop_positive=trailing["positive"],
        trailing_stop_positive_offset=trailing["offset"],
        trailing_only_offset_is_reached=trailing["only_offset"],
        startup_candle_count=startup,
        can_short=can_short_line,
        indicator_code=indicator_code or "        pass",
        entry_code=entry_code,
        exit_code=exit_code,
        extra_imports=extra_imports,
    )


def compile_config(doc: GenomeDocument) -> dict[str, Any]:
    """Generate a FreqTrade config dict from genome body."""
    ex = doc.body.exchange
    risk = doc.body.risk

    config: dict[str, Any] = {
        "stake_currency": "USDT",
        "stake_amount": risk.position_size.amount_usdt or 100,
        "max_open_trades": risk.max_open_trades,
        "dry_run": True,
        "trading_mode": ex.trading_mode,
        "margin_mode": ex.margin_mode or ("isolated" if ex.trading_mode == "futures" else ""),
        "exchange": {
            "name": ex.name,
            "pair_whitelist": list(doc.body.pairs),
        },
        "timeframe": doc.body.timeframe,
    }
    return config


# --- Private helpers ---


def _sanitize_class_name(name: str) -> str:
    """Convert a genome name to a valid Python class name."""
    cleaned = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    cleaned = re.sub(r"_+", "_", cleaned).strip("_")
    if not cleaned or cleaned[0].isdigit():
        cleaned = "Strategy_" + cleaned
    parts = cleaned.split("_")
    return "".join(p.capitalize() for p in parts if p) + "Strategy"


def _signal_to_condition(signal: Any, indicators: set[str]) -> str | None:
    """Convert a FreqHub signal object to a pandas condition expression."""
    if signal is None:
        return None

    sig_type = signal.type if hasattr(signal, "type") else None

    if sig_type == "threshold_cross":
        ind_name = signal.indicator
        params = signal.params or {}
        col = _resolve_indicator_column(ind_name, params)
        indicators.add(json.dumps({"name": ind_name, "params": params}, sort_keys=True))

        cond = signal.condition
        val = signal.value
        if cond == "crosses_below":
            return f"qtpylib.crossed_below(dataframe['{col}'], {val})"
        elif cond == "crosses_above":
            return f"qtpylib.crossed_above(dataframe['{col}'], {val})"
        elif cond in ("below", "<"):
            return f"dataframe['{col}'] < {val}"
        elif cond in ("above", ">"):
            return f"dataframe['{col}'] > {val}"
        elif cond == "<=":
            return f"dataframe['{col}'] <= {val}"
        elif cond == ">=":
            return f"dataframe['{col}'] >= {val}"
        elif cond == "==":
            return f"dataframe['{col}'] == {val}"
        return f"dataframe['{col}'] < {val}"

    elif sig_type == "indicator_cross":
        fast_ind = signal.fast.get("indicator", "ema")
        fast_params = signal.fast.get("params", {})
        slow_ind = signal.slow.get("indicator", "ema")
        slow_params = signal.slow.get("params", {})
        fast_col = _resolve_indicator_column(fast_ind, fast_params)
        slow_col = _resolve_indicator_column(slow_ind, slow_params)
        indicators.add(json.dumps({"name": fast_ind, "params": fast_params}, sort_keys=True))
        indicators.add(json.dumps({"name": slow_ind, "params": slow_params}, sort_keys=True))

        if signal.condition == "crosses_above":
            return f"qtpylib.crossed_above(dataframe['{fast_col}'], dataframe['{slow_col}'])"
        elif signal.condition == "crosses_below":
            return f"qtpylib.crossed_below(dataframe['{fast_col}'], dataframe['{slow_col}'])"
        return f"dataframe['{fast_col}'] > dataframe['{slow_col}']"

    elif sig_type == "composite_and":
        conds = [_signal_to_condition(c, indicators) for c in signal.conditions]
        conds = [c for c in conds if c]
        if not conds:
            return None
        return " &\n            ".join(f"({c})" for c in conds)

    elif sig_type == "composite_or":
        conds = [_signal_to_condition(c, indicators) for c in signal.conditions]
        conds = [c for c in conds if c]
        if not conds:
            return None
        return " |\n            ".join(f"({c})" for c in conds)

    elif sig_type == "pattern":
        return f"dataframe['{signal.pattern}'] > 0"

    elif sig_type == "custom":
        return signal.expression

    return None


def _resolve_indicator_column(indicator_name: str, params: dict[str, Any]) -> str:
    """Resolve the DataFrame column name for an indicator with params."""
    try:
        return resolve_column_name(indicator_name, params)
    except ValueError:
        if params:
            first_val = next(iter(params.values()))
            return f"{indicator_name}_{first_val}"
        return indicator_name


def _needs_qtpylib(signal: Any) -> bool:
    """Check if a signal tree requires qtpylib imports."""
    if signal is None:
        return False
    sig_type = getattr(signal, "type", None)
    if sig_type == "threshold_cross":
        return signal.condition in ("crosses_above", "crosses_below")
    elif sig_type == "indicator_cross":
        return True
    elif sig_type in ("composite_and", "composite_or"):
        return any(_needs_qtpylib(c) for c in signal.conditions)
    return False


def _build_indicator_code(indicators: set[str]) -> str:
    """Generate populate_indicators() body from collected indicator references."""
    seen: set[str] = set()
    lines: list[str] = []

    for raw in sorted(indicators):
        spec = json.loads(raw)
        name = spec["name"]
        params = spec.get("params", {})

        normalized = normalize_params(params)
        try:
            defn, parsed_params = get_indicator(name)
        except ValueError:
            lines.append(f"        # Unknown indicator: {name}")
            continue

        merged = {**defn.default_params, **parsed_params, **normalized}
        col_key = f"{name}_{json.dumps(merged, sort_keys=True)}"
        if col_key in seen:
            continue
        seen.add(col_key)

        valid_keys = set(defn.default_params.keys())
        filtered = {k: v for k, v in merged.items() if k in valid_keys}

        code_lines = defn.generate_code(filtered)
        for cl in code_lines:
            lines.append(f"    {cl}")

    return "\n".join(lines) if lines else ""


def _build_entry_exit_code(condition: str | None, regime_cond: str | None, col_name: str) -> str:
    """Generate a dataframe.loc assignment for an entry/exit signal."""
    if not condition:
        return ""

    full_cond = condition
    if regime_cond:
        full_cond = f"({condition}) &\n            {regime_cond}"

    full_cond += " &\n            (dataframe['volume'] > 0)"

    code = textwrap.dedent(f"""\
        dataframe.loc[
            {full_cond},
            '{col_name}',
        ] = 1""")
    return textwrap.indent(code, "        ")


def _extract_risk(risk: Any) -> tuple[float, dict[str, Any], str]:
    """Extract FreqTrade risk parameters from method-based risk model."""
    stoploss = -0.10
    if risk.stop_loss.method == "fixed_pct":
        stoploss = -(risk.stop_loss.params.get("pct", 0.10))
    elif risk.stop_loss.method == "atr_multiple":
        stoploss = -0.10

    trailing = {
        "stop": False,
        "positive": None,
        "offset": 0.0,
        "only_offset": False,
    }
    if risk.stop_loss.method == "trailing":
        trailing["stop"] = True
        trailing["positive"] = risk.stop_loss.params.get("positive", 0.01)
        trailing["offset"] = risk.stop_loss.params.get("offset", 0.02)
        trailing["only_offset"] = trailing["positive"] is not None and trailing["offset"] > 0

    if risk.take_profit.method == "fixed_pct":
        tp = risk.take_profit.params.get("pct", 0.10)
        roi_str = _format_roi({"0": tp})
    elif risk.take_profit.method == "risk_reward":
        ratio = risk.take_profit.params.get("ratio", 2.0)
        tp = abs(stoploss) * ratio
        roi_str = _format_roi({"0": round(tp, 4)})
    else:
        roi_str = _format_roi({"0": 0.10})

    return stoploss, trailing, roi_str


def _compute_startup_candles(indicators: set[str]) -> int:
    """Determine startup_candle_count from collected indicators."""
    max_period = 30
    for raw in indicators:
        spec = json.loads(raw)
        params = normalize_params(spec.get("params", {}))
        for key in ("timeperiod", "period"):
            if key in params:
                val = int(params[key])
                if val > max_period:
                    max_period = val
    return max_period + 10


def _format_roi(roi: dict[str, float]) -> str:
    """Format ROI dict for Python source code."""
    items = []
    for key, val in sorted(roi.items(), key=lambda x: int(x[0])):
        items.append(f"        {int(key)}: {val}")
    return "{\n" + ",\n".join(items) + ",\n    }"
